# A minimal left prompt
format = """$container$directory$character"""

# move the rest of the prompt to the right
right_format = """$all"""

# Git can be quite slow in large repositories
command_timeout = 1000

[time]
disabled = false

[directory]
fish_style_pwd_dir_length = 1

[memory_usage]
disabled = false

[container]
style = 'bold red'
