- name: Clone git repos
  hosts: linux_workstations
  tasks:
    - name: Create dev directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/dev/"
        state: directory
        mode: "0775"

    - name: Checkout IaC
      ansible.builtin.git:
        repo: git@github.com:briandipalma/iac.git
        dest: "{{ lookup('env', 'HOME') }}/dev/iac"

    - name: Checkout my-data
      ansible.builtin.git:
        repo: git@github.com:briandipalma/my-data.git
        dest: "{{ lookup('env', 'HOME') }}/dev/my-data"

    - name: Copy post-checkout hook
      ansible.builtin.copy:
        src: post-checkout
        dest: "{{ lookup('env', 'HOME') }}/dev/m/mono/.git/hooks/"
        mode: "0775"
