- name: Clone git repos
  hosts: linux_workstations
  tasks:
    - name: Include my vars
      ansible.builtin.include_vars: "{{ lookup('env', 'HOME') }}/dev/my-data/ansible_vars.yml"

    - name: Checkout front-end
      ansible.builtin.git:
        repo: https://briand:{{ gitlab_access_token }}@gitlab.caplin.com/front-end/mono.git
        update: false
        dest: "{{ lookup('env', 'HOME') }}/dev/m/mono"

    - name: Checkout FXAPI
      ansible.builtin.git:
        repo: https://briand:{{ gitlab_access_token }}@gitlab.caplin.com/integration/fx-integration-api.git
        update: false
        dest: "{{ lookup('env', 'HOME') }}/dev/fx-integration-api"

    - name: Copy post-checkout hook
      ansible.builtin.copy:
        src: post-checkout
        dest: "{{ lookup('env', 'HOME') }}/dev/m/mono/.git/hooks/"
        mode: "0775"
