-- lua print(vim.bo.filetype) to find out filetype
-- There seems to be no way to find the name of the treesitter language for the filetype - you just
-- need to know `typescriptreact` means the `tsx` treesitter language...
