---
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - SERVERURL=${WIREGUARD_SERVERURL}
      - SERVERPORT=51820
      - PEERS=briansPhone,briansLaptop
      - PEERDNS=192.168.1.2,192.168.1.3
      - INTERNAL_SUBNET=10.13.13.0
      - LOG_CONFS=true #optional
    volumes:
      - /mnt/storage/appdata/wireguard/config:/config
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped