---
services:
  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    restart: unless-stopped
    environment:
      - TZ=Europe/Dublin
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/storage/appdata/rclone:/config/rclone
      - /mnt/storage/data/pictures/:/data/pictures
    ports:
      - 5572:5572
    command: rcd --rc-web-gui --rc-web-gui-no-open-browser --rc-addr :5572 --rc-user admin --rc-pass yourpassword --rc-serve