---
services:
  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    restart: unless-stopped
    environment:
      - TZ=Europe/Dublin
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/storage/appdata/rclone:/config/rclone:ro
