---
gui:
  expandFocusedSidePanel: true
  enlargedSideViewLocation: top
  theme:
    selectedLineBgColor:
      - black
  showCommandLog: false
  nerdFontsVersion: "3"
  windowSize: "half"
  portraitMode: "always"

git:
  paging:
    colorArg: always
    pager: delta --paging=never

customCommands:
  - key: "P"
    command: "git push --force-with-lease -u origin {{.CheckedOutBranch.Name}}"
    context: "global"
    loadingText: "Pushing changes using force-with-lease"

os:
  editPreset: "nvim-remote"

startuppopupversion: 1
