---
git:
  diffRenderers:
    - colorArg: always
      command: delta --paging=never --side-by-side --line-numbers
customCommands:
  - key: "P"
    command: "git push --force-with-lease -u origin {{.CheckedOutBranch.Name}}"
    context: "global"
    loadingText: "Pushing changes using force-with-lease"
os:
  editPreset: "nvim-remote"
keybinding:
  files:
    amendLastCommit: a
    toggleStagedAll: A
startuppopupversion: 1
