---
gui:
  expandFocusedSidePanel: true
  portraitMode: "always"
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - yellow
      - bold
    selectedLineBgColor:
      - black

git:
  paging:
    colorArg: always
    pager: delta --paging=never

customCommands:
  - key: "P"
    command: "git push --force-with-lease -u origin {{.CheckedOutBranch.Name}}"
    context: "global"
    loadingText: "Pushing changes using force-with-lease"

os:
  editPreset: "nvim-remote"

startuppopupversion: 1
