---
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    security_opt:
      # Prevent escalation of privileges after the container is started
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /mnt/storage/appdata/syncthing/config:/config
      - /mnt/storage/data/music:/music
      - /mnt/storage/data/pictures:/pictures
      - /mnt/storage/data/videos:/videos
      - /mnt/storage/sync/brians_samsung_s20_fe_camera:/brians_samsung_s20_fe_camera
      - /mnt/storage/sync/brians_samsung_s20_fe_whatsapp_media:/brians_samsung_s20_fe_whatsapp_media
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.syncthing.rule=Host(`sync.test`)
      - traefik.http.services.sync.loadbalancer.server.port=8384
      - traefik.http.routers.syncthing.middlewares=local-ip-allowlist
    networks:
      - proxy_network

networks:
  proxy_network:
    name: proxy_network
    external: true
