[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.19999999552965164
    center = [ "taskbar", "notifications" ]
    end = [ "media", "tray", "network", "bluetooth", "volume", "brightness", "battery", "session" ]
    margin_ends = 0
    radius = 0
    scale = 1.4500000141561031
    start = [ "control-center", "clock" ]

[location]
address = "Dublin, Ireland"

[nightlight]
enabled = true

[plugins]
enabled = [ "kenn/keybind-cheatsheet" ]

[wallpaper]
enabled = false

    [wallpaper.default]
    path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

    [wallpaper.last]
    path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

[widget.media]
hide_when_no_media = true

[widget.taskbar]
anchor = true
group_by_workspace = true
inactive_opacity = 0.65000000000000002
only_active_workspace = false
workspace_group_capsule = true

[widget.workspaces]
label_source = "name"
max_label_chars = 8
