---
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'Europe/Dublin'
      # Set a password to access the web interface. Not setting one will result
      # in a random password being assigned
      FTLCONF_webserver_api_password: ${PIHOLE_WEB_PASSWD}
      # If using Docker's default `bridge` network setting the dns listening
      # mode should be set to 'ALL'
      FTLCONF_dns_listeningMode: 'ALL'
    # Volumes store your data between container upgrades
    volumes:
      - /mnt/storage/appdata/pihole:/etc/pihole
    cap_add:
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`dnsone.test`)
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - traefik.http.routers.pihole.middlewares=local-ip-allowlist
      - docker-volume-backup.archive-pre=cd /etc/pihole
    networks:
      - proxy_network

  backup:
    image: offen/docker-volume-backup:v2
    restart: always
    environment:
      - BACKUP_CRON_EXPRESSION=0 2 * * * # Runs daily at 2:00 AM UTC
      - BACKUP_RETENTION_DAYS=7
      - BACKUP_FILENAME=pihole-one-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_PRUNING_PREFIX=pihole-one-backup-
      # Excludes any file that DOES NOT end with .sql
      # - BACKUP_EXCLUDE_REGEXP=^((?!\.zip$).)*$

      - AWS_S3_BUCKET_NAME=dipalma-docker-backups
      - AWS_ENDPOINT=s3.eu-central-003.backblazeb2.com
      - AWS_ACCESS_KEY_ID=${DOCKER_BACKUPS_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${DOCKER_BACKUPS_AWS_SECRET_ACCESS_KEY}
    volumes:
      - /mnt/storage/appdata/pihole/backup.zip:/backup/pihole-one:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  proxy_network:
    name: proxy_network
    external: true